import { decisionTraceRepository } from '../repositories/decisionTrace.repository.ts';
import { resourceAuth } from '../lib/resourceAuth.ts';
import { auditRepository } from '../repositories/audit.repository.ts';
import { BankingError } from '../lib/errors.ts';
import { SafeUser } from './auth.service.ts';
import {
  DecisionTraceDTO,
  DecisionTraceEvidenceDTO,
  DecisionTraceSourceNodeDTO,
  DecisionComparisonDTO,
  DecisionAnalyticsSummaryDTO,
} from '../types/decisionTrace.types.ts';

function formatFreshness(timestamp: Date | string | null | undefined): string {
  if (!timestamp) return 'Freshness unavailable';
  const time = new Date(timestamp).getTime();
  if (isNaN(time)) return 'Freshness unavailable';

  const diffMs = Date.now() - time;
  if (diffMs < 0) return 'Just now';
  const diffSec = Math.floor(diffMs / 1000);
  if (diffSec < 60) return `${diffSec}s ago`;
  const diffMin = Math.floor(diffSec / 60);
  if (diffMin < 60) return `${diffMin} min ago`;
  const diffHours = Math.floor(diffMin / 60);
  if (diffHours < 24) return `${diffHours}h ago`;
  const diffDays = Math.floor(diffHours / 24);
  return `${diffDays}d ago`;
}

function parseJsonSafe<T>(val: string | null | undefined, defaultVal: T): T {
  if (!val) return defaultVal;
  try {
    return JSON.parse(val);
  } catch {
    return defaultVal;
  }
}

export const decisionTraceService = {
  /**
   * Enterprise Decision Trace Ingestion
   * Records decisions generated by existing engines with full evidence and source graph
   */
  async recordDecisionTrace(
    params: {
      decisionId?: string;
      customerId?: number | null;
      userId?: number | null;
      sourceModule: string;
      sourceEngine: string;
      decisionType: string;
      decisionStatus?: string;
      recommendationTitle: string;
      recommendationSummary: string;
      recommendationPayload?: Record<string, any> | null;
      decisionMode?: 'DETERMINISTIC' | 'AI_GENERATED' | 'HYBRID' | 'SYSTEM_RULE';
      confidence?: string | number | null;
      confidenceBasis?: string;
      limitations?: string[];
      dataAsOf?: Date;
      actionTitle?: string | null;
      actionType?: string | null;
      actionPayload?: Record<string, any> | null;
      evidence?: Array<{
        evidenceType: string;
        sourceEngine: string;
        sourceEntityType: string;
        sourceEntityId: string;
        sourceField?: string | null;
        description: string;
        observedValue: string;
        previousValue?: string | null;
        changeDirection?: 'INCREASE' | 'DECREASE' | 'STABLE' | 'TRIGGERED' | 'RESOLVED' | 'BREACHED' | null;
        contributionType?: 'PRIMARY' | 'SUPPORTING' | 'CONTEXT' | 'CONSTRAINT' | 'NEGATIVE_SIGNAL';
        contributionWeight?: string | null;
        dataAsOf?: Date;
      }>;
      sourceChain?: Array<{
        sourceType: string;
        sourceId: string;
        sourceEngine: string;
        description: string;
        sourceTimestamp?: Date;
        authorizationScope?: string;
        orderIndex?: number;
      }>;
    },
    user?: SafeUser,
    requestId: string = 'REQ-DECISION-RECORD'
  ) {
    const decisionCode =
      params.decisionId ||
      `DT-${new Date().toISOString().slice(0, 10).replace(/-/g, '')}-${Math.floor(10000 + Math.random() * 90000)}`;

    const traceData = {
      decisionId: decisionCode,
      customerId: params.customerId || null,
      userId: params.userId || (user ? user.id : null),
      sourceModule: params.sourceModule,
      sourceEngine: params.sourceEngine,
      decisionType: params.decisionType,
      decisionStatus: params.decisionStatus || 'PENDING',
      recommendationTitle: params.recommendationTitle,
      recommendationSummary: params.recommendationSummary,
      recommendationPayload: params.recommendationPayload
        ? JSON.stringify(params.recommendationPayload)
        : null,
      decisionMode: params.decisionMode || 'DETERMINISTIC',
      confidence: params.confidence !== undefined && params.confidence !== null ? String(params.confidence) : null,
      confidenceBasis:
        params.confidenceBasis ||
        (params.decisionMode === 'HYBRID'
          ? 'Deterministic evidence + AI-generated explanation'
          : params.decisionMode === 'AI_GENERATED'
          ? 'AI generative synthesis'
          : 'Rule-based'),
      limitations: params.limitations ? JSON.stringify(params.limitations) : JSON.stringify([
        'This recommendation is based on available CRM data.',
        'This does not predict customer behavior.',
        'This does not constitute a credit decision.',
        'This recommendation requires human review.',
      ]),
      actionTitle: params.actionTitle || null,
      actionType: params.actionType || null,
      actionPayload: params.actionPayload ? JSON.stringify(params.actionPayload) : null,
      generatedAt: new Date(),
      dataAsOf: params.dataAsOf || new Date(),
    };

    const evidenceList = (params.evidence || []).map((e: any) => ({
      evidenceType: e.evidenceType || 'FACT',
      sourceEngine: e.sourceEngine || params.sourceEngine || 'COREvia Intelligence Engine',
      sourceEntityType: e.sourceEntityType || 'CUSTOMER',
      sourceEntityId: String(e.sourceEntityId || params.customerId || 'GLOBAL'),
      sourceField: e.sourceField || null,
      description: e.description || e.title || 'Evidence item',
      observedValue: String(e.observedValue ?? e.title ?? 'OBSERVED'),
      previousValue: e.previousValue ? String(e.previousValue) : null,
      changeDirection: e.changeDirection || null,
      contributionType: e.contributionType || 'SUPPORTING',
      contributionWeight: e.contributionWeight || e.weight || null,
      dataAsOf: e.dataAsOf || new Date(),
    }));

    const rawSources = params.sourceChain || (params as any).sourceNodes || [];
    const sourceNodesList = rawSources.map((s: any, idx: number) => ({
      orderIndex: s.orderIndex ?? idx,
      sourceType: s.sourceType || 'SYSTEM',
      sourceId: String(s.sourceId || 'NODE'),
      sourceEngine: s.sourceEngine || params.sourceEngine || 'COREvia Engine',
      description: s.description || 'Source system node',
      sourceTimestamp: s.sourceTimestamp || new Date(),
      authorizationScope: s.authorizationScope || 'BRANCH',
    }));

    const inserted = await decisionTraceRepository.createTrace(traceData, evidenceList, sourceNodesList);

    // Audit trace creation
    await auditRepository.createLog({
      actorId: user ? (user.employeeId || String(user.id)) : 'SYSTEM_INTELLIGENCE_ENGINE',
      actorName: user ? (user.name || 'COREvia Banker') : 'COREvia Intelligence Engine',
      action: 'DECISION_TRACE_CREATED',
      resourceType: 'DECISION_TRACE',
      resourceId: decisionCode,
      requestId,
      outcome: 'SUCCESS',
      metadata: {
        customerId: params.customerId,
        sourceEngine: params.sourceEngine,
        decisionType: params.decisionType,
        decisionMode: traceData.decisionMode,
      },
    });

    return inserted;
  },

  /**
   * Retrieve a Decision Trace with strict resource-level authorization
   */
  async getDecisionTrace(
    codeOrId: string | number,
    user: SafeUser,
    requestId: string = 'REQ-DECISION-GET'
  ): Promise<DecisionTraceDTO> {
    if (!user) {
      throw new BankingError('UNAUTHENTICATED', 'Authentication required to inspect decision trace.', 401);
    }

    const record = await decisionTraceRepository.findByCodeOrId(codeOrId);
    if (!record) {
      throw new BankingError('DECISION_TRACE_NOT_FOUND', `Decision trace '${codeOrId}' does not exist.`, 404);
    }

    // 1. Authorize customer access if customer-scoped
    if (record.trace.customerId) {
      await resourceAuth.authorizeCustomer(user, record.trace.customerId, 'READ', requestId);
    }

    // 2. Audit access
    await auditRepository.createLog({
      actorId: user.employeeId,
      actorName: user.name,
      action: 'DECISION_TRACE_VIEWED',
      resourceType: 'DECISION_TRACE',
      resourceId: record.trace.decisionId,
      requestId,
      outcome: 'SUCCESS',
      metadata: {
        customerId: record.trace.customerId,
        sourceEngine: record.trace.sourceEngine,
      },
    });

    // 3. Format response DTO with freshness breakdown
    const t = record.trace;
    const sourceChainDTO: DecisionTraceSourceNodeDTO[] = record.sourceNodes.map((s) => ({
      id: s.id,
      decisionTraceId: s.decisionTraceId,
      orderIndex: s.orderIndex,
      sourceType: s.sourceType,
      sourceId: s.sourceId,
      sourceEngine: s.sourceEngine,
      description: s.description,
      sourceTimestamp: s.sourceTimestamp.toISOString(),
      authorizationScope: s.authorizationScope,
      freshnessLabel: formatFreshness(s.sourceTimestamp),
      createdAt: s.createdAt.toISOString(),
    }));

    const evidenceDTO: DecisionTraceEvidenceDTO[] = record.evidence.map((e) => ({
      id: e.id,
      decisionTraceId: e.decisionTraceId,
      evidenceType: e.evidenceType as any,
      sourceEngine: e.sourceEngine,
      sourceEntityType: e.sourceEntityType,
      sourceEntityId: e.sourceEntityId,
      sourceField: e.sourceField,
      description: e.description,
      observedValue: e.observedValue,
      previousValue: e.previousValue,
      changeDirection: e.changeDirection as any,
      contributionType: e.contributionType as any,
      contributionWeight: e.contributionWeight,
      dataAsOf: e.dataAsOf.toISOString(),
      createdAt: e.createdAt.toISOString(),
    }));

    // Data freshness summary per contributing engine
    const freshnessMap = new Map<string, Date>();
    for (const s of record.sourceNodes) {
      const existing = freshnessMap.get(s.sourceEngine);
      if (!existing || s.sourceTimestamp.getTime() > existing.getTime()) {
        freshnessMap.set(s.sourceEngine, s.sourceTimestamp);
      }
    }
    for (const e of record.evidence) {
      const existing = freshnessMap.get(e.sourceEngine);
      if (!existing || e.dataAsOf.getTime() > existing.getTime()) {
        freshnessMap.set(e.sourceEngine, e.dataAsOf);
      }
    }

    const freshnessBreakdown = Array.from(freshnessMap.entries()).map(([engine, ts]) => ({
      engine,
      lastRefreshed: ts.toISOString(),
      freshnessLabel: formatFreshness(ts),
    }));

    const dataFreshnessSummary =
      freshnessBreakdown.length > 0
        ? freshnessBreakdown.map((f) => `${f.engine}: ${f.freshnessLabel}`).join(' · ')
        : formatFreshness(t.dataAsOf);

    return {
      id: t.id,
      decisionId: t.decisionId,
      customerId: t.customerId,
      customerName: record.customerName,
      customerCif: record.customerCif,
      userId: t.userId,
      sourceModule: t.sourceModule,
      sourceEngine: t.sourceEngine,
      decisionType: t.decisionType as any,
      decisionStatus: t.decisionStatus as any,
      recommendationTitle: t.recommendationTitle,
      recommendationSummary: t.recommendationSummary,
      recommendationPayload: parseJsonSafe(t.recommendationPayload, null),
      decisionMode: t.decisionMode as any,
      confidence: t.confidence,
      confidenceBasis: t.confidenceBasis,
      limitations: parseJsonSafe(t.limitations, []),
      actionTitle: t.actionTitle,
      actionType: t.actionType,
      actionPayload: parseJsonSafe(t.actionPayload, null),
      confirmedById: t.confirmedById,
      confirmedByName: record.confirmedByName,
      confirmedAt: t.confirmedAt ? t.confirmedAt.toISOString() : null,
      executionStatus: t.executionStatus as any,
      executedAt: t.executedAt ? t.executedAt.toISOString() : null,
      outcome: t.outcome,
      actionOutcome: t.outcome,
      generatedAt: t.generatedAt.toISOString(),
      dataAsOf: t.dataAsOf.toISOString(),
      dataFreshnessSummary,
      expiresAt: t.expiresAt ? t.expiresAt.toISOString() : null,
      createdAt: t.createdAt.toISOString(),
      updatedAt: t.updatedAt.toISOString(),
      evidence: evidenceDTO,
      sourceChain: sourceChainDTO,
      freshnessBreakdown,
    };
  },

  /**
   * Retrieve evidence list for a trace
   */
  async getDecisionEvidence(
    codeOrId: string | number,
    user: SafeUser,
    requestId: string = 'REQ-DECISION-EVIDENCE'
  ): Promise<DecisionTraceEvidenceDTO[]> {
    const trace = await this.getDecisionTrace(codeOrId, user, requestId);

    await auditRepository.createLog({
      actorId: user.employeeId,
      actorName: user.name,
      action: 'DECISION_TRACE_EVIDENCE_VIEWED',
      resourceType: 'DECISION_TRACE',
      resourceId: trace.decisionId,
      requestId,
      outcome: 'SUCCESS',
      metadata: { evidenceCount: trace.evidence?.length || 0 },
    });

    return trace.evidence || [];
  },

  /**
   * Retrieve source chain nodes for a trace
   */
  async getDecisionSources(
    codeOrId: string | number,
    user: SafeUser,
    requestId: string = 'REQ-DECISION-SOURCES'
  ): Promise<DecisionTraceSourceNodeDTO[]> {
    const trace = await this.getDecisionTrace(codeOrId, user, requestId);

    await auditRepository.createLog({
      actorId: user.employeeId,
      actorName: user.name,
      action: 'DECISION_TRACE_SOURCES_VIEWED',
      resourceType: 'DECISION_TRACE',
      resourceId: trace.decisionId,
      requestId,
      outcome: 'SUCCESS',
      metadata: { sourceNodeCount: trace.sourceChain?.length || 0 },
    });

    return trace.sourceChain || [];
  },

  /**
   * Chronological decision history for a customer
   */
  async getDecisionHistory(
    customerIdOrCode: number | string,
    user: SafeUser,
    requestId: string = 'REQ-DECISION-HISTORY'
  ) {
    if (!user) {
      throw new BankingError('UNAUTHENTICATED', 'Authentication required.', 401);
    }

    let customerId: number;
    if (typeof customerIdOrCode === 'string' && customerIdOrCode.startsWith('DT-')) {
      const traceRecord = await decisionTraceRepository.findByCodeOrId(customerIdOrCode);
      if (!traceRecord || !traceRecord.trace.customerId) {
        throw new BankingError('DECISION_TRACE_NOT_FOUND', `Trace '${customerIdOrCode}' does not have a customer context.`, 404);
      }
      customerId = traceRecord.trace.customerId;
    } else {
      customerId = Number(customerIdOrCode);
    }

    // Authorize customer
    await resourceAuth.authorizeCustomer(user, customerId, 'READ', requestId);

    const { items, total } = await decisionTraceRepository.findByCustomers([customerId], {
      limit: 50,
    });

    const historyTimeline = items.map((row) => ({
      id: row.trace.id,
      decisionId: row.trace.decisionId,
      sourceEngine: row.trace.sourceEngine,
      decisionType: row.trace.decisionType,
      decisionStatus: row.trace.decisionStatus,
      recommendationTitle: row.trace.recommendationTitle,
      recommendationSummary: row.trace.recommendationSummary,
      decisionMode: row.trace.decisionMode,
      confidence: row.trace.confidence,
      confidenceBasis: row.trace.confidenceBasis,
      actionTitle: row.trace.actionTitle,
      confirmedAt: row.trace.confirmedAt ? row.trace.confirmedAt.toISOString() : null,
      executionStatus: row.trace.executionStatus,
      outcome: row.trace.outcome,
      generatedAt: row.trace.generatedAt.toISOString(),
      freshnessLabel: formatFreshness(row.trace.generatedAt),
    }));

    return {
      customerId,
      total,
      history: historyTimeline,
      timeline: historyTimeline,
    };
  },

  /**
   * Compare two decision traces (e.g. earlier recommendation vs current)
   * Prevents cross-customer comparison unless officer has portfolio-wide authorization
   */
  async compareDecisionTraces(
    traceId1: string | number,
    traceId2: string | number,
    user: SafeUser,
    requestId: string = 'REQ-DECISION-COMPARE'
  ): Promise<DecisionComparisonDTO> {
    const traceA = await this.getDecisionTrace(traceId1, user, requestId);
    const traceB = await this.getDecisionTrace(traceId2, user, requestId);

    // Cross-customer comparison prevention
    if (traceA.customerId && traceB.customerId && traceA.customerId !== traceB.customerId) {
      if (user.role !== 'ADMINISTRATOR' && user.role !== 'BRANCH_MANAGER' && user.role !== 'ANALYST') {
        throw new BankingError(
          'FORBIDDEN_SCOPE',
          'Cross-customer decision comparison requires portfolio-wide oversight authorization.',
          403
        );
      }
    }

    const evidenceA = traceA.evidence || [];
    const evidenceB = traceB.evidence || [];

    // Comparison logic
    const bDescriptions = new Set(evidenceB.map((e) => e.description.toLowerCase().trim()));
    const aDescriptions = new Set(evidenceA.map((e) => e.description.toLowerCase().trim()));

    const evidenceAdded = evidenceB.filter((e) => !aDescriptions.has(e.description.toLowerCase().trim()));
    const evidenceRemoved = evidenceA.filter((e) => !bDescriptions.has(e.description.toLowerCase().trim()));
    const evidenceCommon = evidenceB.filter((e) => aDescriptions.has(e.description.toLowerCase().trim()));

    // Metric / score changes comparison
    const scoreChanges: DecisionComparisonDTO['scoreChanges'] = [];
    for (const eB of evidenceB) {
      if (eB.evidenceType === 'SCORE_CHANGE' || eB.evidenceType === 'CUSTOMER_FACT') {
        const matchingA = evidenceA.find(
          (eA) => eA.sourceEngine === eB.sourceEngine && eA.sourceField === eB.sourceField
        );
        if (matchingA && matchingA.observedValue !== eB.observedValue) {
          const numA = parseFloat(matchingA.observedValue);
          const numB = parseFloat(eB.observedValue);
          const delta = !isNaN(numA) && !isNaN(numB) ? numB - numA : undefined;

          scoreChanges.push({
            engine: eB.sourceEngine,
            metric: eB.sourceField || eB.description,
            baseValue: matchingA.observedValue,
            comparedValue: eB.observedValue,
            delta,
          });
        }
      }
    }

    const summaryParts: string[] = [];
    if (evidenceAdded.length > 0) summaryParts.push(`${evidenceAdded.length} new evidence items observed`);
    if (evidenceRemoved.length > 0) summaryParts.push(`${evidenceRemoved.length} prior evidence items cleared`);
    if (scoreChanges.length > 0) summaryParts.push(`${scoreChanges.length} metric value changes detected`);
    if (traceA.decisionStatus !== traceB.decisionStatus) {
      summaryParts.push(`Status transitioned from ${traceA.decisionStatus} to ${traceB.decisionStatus}`);
    }

    await auditRepository.createLog({
      actorId: user.employeeId,
      actorName: user.name,
      action: 'DECISION_TRACE_COMPARED',
      resourceType: 'DECISION_TRACE',
      resourceId: `${traceA.decisionId}:${traceB.decisionId}`,
      requestId,
      outcome: 'SUCCESS',
      metadata: {
        traceA: traceA.decisionId,
        traceB: traceB.decisionId,
        addedCount: evidenceAdded.length,
        removedCount: evidenceRemoved.length,
      },
    });

    return {
      baseTrace: traceA,
      comparedTrace: traceB,
      baseDecisionId: traceA.decisionId,
      targetDecisionId: traceB.decisionId,
      evidenceAdded,
      evidenceRemoved,
      evidenceCommon,
      scoreChanges,
      metricDeltas: scoreChanges,
      sourceDifferences: summaryParts,
      summaryOfDifferences:
        summaryParts.length > 0 ? summaryParts.join(' • ') : 'No structural differences detected between traces.',
      summary: summaryParts.length > 0 ? summaryParts.join(' • ') : 'No structural differences detected between traces.',
    };
  },

  /**
   * Confirm proposed decision action
   */
  async confirmDecisionAction(
    codeOrId: string | number,
    notesOrUser: string | SafeUser,
    maybeUser?: SafeUser,
    requestId: string = 'REQ-DECISION-CONFIRM'
  ) {
    const user: SafeUser = maybeUser || (notesOrUser as SafeUser);
    const notes: string = typeof notesOrUser === 'string' ? notesOrUser : '';

    const trace = await this.getDecisionTrace(codeOrId, user, requestId);

    if (trace.decisionStatus === 'EXECUTED') {
      throw new BankingError('INVALID_STATE', 'Decision action has already been executed.', 400);
    }

    const updated = await decisionTraceRepository.updateStatus(trace.id, 'CONFIRMED', {
      confirmedById: user.id,
      confirmedAt: new Date(),
      outcome: notes || trace.outcome,
    });

    await auditRepository.createLog({
      actorId: user.employeeId,
      actorName: user.name,
      action: 'DECISION_TRACE_ACTION_CONFIRMED',
      resourceType: 'DECISION_TRACE',
      resourceId: trace.decisionId,
      requestId,
      outcome: 'SUCCESS',
      metadata: {
        confirmedBy: user.employeeId,
        actionTitle: trace.actionTitle,
        notes,
      },
    });

    return await this.getDecisionTrace(trace.id, user, requestId);
  },

  /**
   * Reject or dismiss proposed decision action
   */
  async rejectDecisionAction(
    codeOrId: string | number,
    reason: string,
    user: SafeUser,
    requestId: string = 'REQ-DECISION-REJECT'
  ) {
    const trace = await this.getDecisionTrace(codeOrId, user, requestId);

    const updated = await decisionTraceRepository.updateStatus(trace.id, 'DISMISSED', {
      outcome: reason || 'Officer dismissed recommendation.',
    });

    await auditRepository.createLog({
      actorId: user.employeeId,
      actorName: user.name,
      action: 'DECISION_TRACE_ACTION_REJECTED',
      resourceType: 'DECISION_TRACE',
      resourceId: trace.decisionId,
      requestId,
      outcome: 'SUCCESS',
      metadata: {
        rejectedBy: user.employeeId,
        reason,
      },
    });

    return await this.getDecisionTrace(trace.id, user, requestId);
  },

  /**
   * Execute confirmed decision action and record verified outcome
   */
  async executeDecisionAction(
    codeOrId: string | number,
    payloadOrOutcome: any,
    outcomeOrUser?: string | SafeUser,
    maybeUser?: SafeUser,
    requestId: string = 'REQ-DECISION-EXECUTE'
  ) {
    let outcomeText = '';
    let user: SafeUser;

    if (maybeUser) {
      outcomeText = typeof outcomeOrUser === 'string' ? outcomeOrUser : JSON.stringify(payloadOrOutcome);
      user = maybeUser;
    } else if (typeof outcomeOrUser === 'object' && outcomeOrUser !== null && 'employeeId' in outcomeOrUser) {
      user = outcomeOrUser as SafeUser;
      outcomeText = typeof payloadOrOutcome === 'string' ? payloadOrOutcome : JSON.stringify(payloadOrOutcome);
    } else {
      outcomeText = typeof payloadOrOutcome === 'string' ? payloadOrOutcome : JSON.stringify(payloadOrOutcome);
      user = (outcomeOrUser as any) || ({} as SafeUser);
    }

    const trace = await this.getDecisionTrace(codeOrId, user, requestId);

    const updated = await decisionTraceRepository.updateStatus(trace.id, 'EXECUTED', {
      executionStatus: 'SUCCESS',
      executedAt: new Date(),
      outcome: outcomeText || 'Action successfully completed in core banking workflow.',
    });

    await auditRepository.createLog({
      actorId: user.employeeId,
      actorName: user.name,
      action: 'DECISION_TRACE_ACTION_EXECUTED',
      resourceType: 'DECISION_TRACE',
      resourceId: trace.decisionId,
      requestId,
      outcome: 'SUCCESS',
      metadata: {
        executedBy: user.employeeId,
        outcome: outcomeText,
      },
    });

    return await this.getDecisionTrace(trace.id, user, requestId);
  },

  /**
   * List decision traces with pagination & filters
   */
  async listDecisionTraces(
    params: {
      customerId?: number;
      sourceEngine?: string;
      decisionType?: string;
      decisionStatus?: string;
      limit?: number;
      offset?: number;
    },
    user: SafeUser,
    requestId: string = 'REQ-DECISION-LIST'
  ) {
    if (!user) {
      throw new BankingError('UNAUTHENTICATED', 'Authentication required.', 401);
    }

    let customerIds: number[] | null = null;
    if (params.customerId) {
      await resourceAuth.authorizeCustomer(user, params.customerId, 'READ', requestId);
      customerIds = [params.customerId];
    } else if (user.role === 'RELATIONSHIP_MANAGER') {
      // Authorize only assigned customers
      customerIds = await resourceAuth.getAuthorizedCustomerIds(user);
    }

    const { items, total } = await decisionTraceRepository.findByCustomers(customerIds, params);

    return {
      total,
      items: items.map((r) => ({
        id: r.trace.id,
        decisionId: r.trace.decisionId,
        customerId: r.trace.customerId,
        customerName: r.customerName,
        customerCif: r.customerCif,
        sourceModule: r.trace.sourceModule,
        sourceEngine: r.trace.sourceEngine,
        decisionType: r.trace.decisionType,
        decisionStatus: r.trace.decisionStatus,
        recommendationTitle: r.trace.recommendationTitle,
        recommendationSummary: r.trace.recommendationSummary,
        decisionMode: r.trace.decisionMode,
        confidence: r.trace.confidence,
        confidenceBasis: r.trace.confidenceBasis,
        actionTitle: r.trace.actionTitle,
        actionType: r.trace.actionType,
        confirmedByName: r.confirmedByName,
        confirmedAt: r.trace.confirmedAt ? r.trace.confirmedAt.toISOString() : null,
        executionStatus: r.trace.executionStatus,
        executedAt: r.trace.executedAt ? r.trace.executedAt.toISOString() : null,
        outcome: r.trace.outcome,
        generatedAt: r.trace.generatedAt.toISOString(),
        freshnessLabel: formatFreshness(r.trace.generatedAt),
      })),
    };
  },

  /**
   * Search traces across authorized customer portfolio
   */
  async searchDecisionTraces(
    query: string,
    user: SafeUser,
    requestId: string = 'REQ-DECISION-SEARCH'
  ) {
    if (!user) return [];

    let customerIds: number[] | null = null;
    if (user.role === 'RELATIONSHIP_MANAGER') {
      customerIds = await resourceAuth.getAuthorizedCustomerIds(user);
    }

    const rows = await decisionTraceRepository.searchTraces(query, customerIds);
    return rows.map((r) => ({
      id: r.trace.id,
      decisionId: r.trace.decisionId,
      customerId: r.trace.customerId,
      customerName: r.customerName,
      customerCif: r.customerCif,
      decisionType: r.trace.decisionType,
      recommendationTitle: r.trace.recommendationTitle,
      decisionStatus: r.trace.decisionStatus,
      generatedAt: r.trace.generatedAt.toISOString(),
    }));
  },

  /**
   * Analytics breakdown (descriptive only, no predictive fabrication)
   */
  async getAnalytics(user: SafeUser, requestId: string = 'REQ-DECISION-ANALYTICS') {
    if (!user) {
      throw new BankingError('UNAUTHENTICATED', 'Authentication required.', 401);
    }

    let customerIds: number[] | null = null;
    if (user.role === 'RELATIONSHIP_MANAGER') {
      customerIds = await resourceAuth.getAuthorizedCustomerIds(user);
    }

    return await decisionTraceRepository.getAnalytics(customerIds);
  },
};
